# Generated by Django 3.0.3 on 2020-03-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ('-created',), 'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.RemoveField(
            model_name='master',
            name='last_name',
        ),
    ]
