# Generated by Django 3.0.3 on 2020-02-19 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Nazvanie_kategorii')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активность категории')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
            ],
            options={
                'verbose_name': 'Категория работ',
                'verbose_name_plural': 'Категории работ',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование работ')),
                ('slug', models.SlugField(max_length=200, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, upload_to='offers/%Y/%m/%d', verbose_name='Фото')),
                ('description', models.TextField(blank=True, max_length=512, verbose_name='Описание работ')),
                ('price', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=10, null=True, verbose_name='Цена работы')),
                ('start_time', models.DateField(blank=True, default=None, null=True, verbose_name='Дата начала работ')),
                ('end_time', models.DateField(blank=True, default=None, null=True, verbose_name='Дата окончания работ')),
                ('available', models.BooleanField(default=False, verbose_name='Актуальность заказа')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='mygsp.Category', verbose_name='Категория работ')),
            ],
            options={
                'verbose_name': 'Предложение о работе',
                'verbose_name_plural': 'Предложения о работе',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
