# Generated by Django 3.0.3 on 2020-02-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygsp', '0003_auto_20200219_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=128, null=True, verbose_name='Емейл'),
        ),
        migrations.AddField(
            model_name='offer',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Имя заказчика'),
        ),
        migrations.AddField(
            model_name='offer',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Фамилия заказчика'),
        ),
        migrations.AddField(
            model_name='offer',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Отчество заказчика'),
        ),
        migrations.AddField(
            model_name='offer',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Номер тел.'),
        ),
    ]
