# Generated by Django 3.0.3 on 2020-02-24 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygsp', '0004_auto_20200219_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('-created', 'name'), 'verbose_name': 'Предложение о работе', 'verbose_name_plural': 'Предложения о работе'},
        ),
    ]
