# Generated by Django 3.0.3 on 2020-03-09 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Nazvanie_kategorii')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активность категории')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
            ],
            options={
                'verbose_name': 'Категория рекламы',
                'verbose_name_plural': 'Категории реклам',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название подкатегории')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Nazvanie_podkategorii')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активность категории')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ad.Category', verbose_name='Категория рекламы')),
            ],
            options={
                'verbose_name': 'Подкатегория рекламы',
                'verbose_name_plural': 'Подкатегории реклам',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Название рекламодателя')),
                ('slug', models.SlugField(max_length=200, verbose_name='Nazvanie_reklamodatelya')),
                ('country', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Страна')),
                ('region', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Регион')),
                ('town', models.CharField(db_index=True, max_length=200, verbose_name='Город')),
                ('address', models.TextField(blank=True, max_length=512, verbose_name='Адрес')),
                ('site', models.URLField(blank=True, default=None, max_length=1024, null=None, verbose_name='Сайт')),
                ('phone', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Номер тел.')),
                ('email', models.EmailField(blank=True, default=None, max_length=128, null=True, verbose_name='Емейл')),
                ('photo', models.ImageField(blank=True, upload_to='promotions_photos/%Y/%m/%d', verbose_name='Фото')),
                ('logotype', models.ImageField(blank=True, upload_to='promotions_logotypes/%Y/%m/%d', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, max_length=512, verbose_name='Описание деятельности')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность рекламы')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачен показ рекламы?')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='ad.Category', verbose_name='Категория рекламы')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='ad.SubCategory', verbose_name='Податегория рекламы')),
            ],
            options={
                'verbose_name': 'Рекламирование',
                'verbose_name_plural': 'Реламирование',
                'ordering': ('-created', 'name'),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
