# Generated by Django 3.0.3 on 2020-03-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='schedule_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня (конец)'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='schedule_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня (начало)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='town',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Город'),
        ),
    ]
