# Generated by Django 3.0.3 on 2020-03-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_auto_20200309_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='subcategory_2',
            field=models.ManyToManyField(blank=True, null=True, to='ad.Category', verbose_name='Категория рекламы_2'),
        ),
    ]
