# Generated by Django 3.0.3 on 2020-03-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_promotion_subcategory_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='subcategory_2',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='category',
        ),
        migrations.AddField(
            model_name='promotion',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='ad.Category', verbose_name='Категория рекламы'),
        ),
    ]
