# Generated by Django 3.0.3 on 2020-04-09 14:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Подкатегория')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Nazvanie_kategorii')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность категории')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='reclame.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория -> Подкатегория',
                'verbose_name_plural': 'Категории -> Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Название рекламодателя')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Nazvanie_reklamodatelya')),
                ('country', models.CharField(blank=True, default='Россия', max_length=200, null=True, verbose_name='Страна')),
                ('region', models.CharField(blank=True, default='Курская область', max_length=200, null=True, verbose_name='Регион')),
                ('town', models.CharField(blank=True, default='Курск', max_length=200, null=True, verbose_name='Город')),
                ('site', models.URLField(blank=True, default=None, max_length=1024, null=None, verbose_name='Сайт')),
                ('email', models.EmailField(blank=True, default=None, max_length=128, null=True, verbose_name='Емейл')),
                ('photo', models.ImageField(blank=True, upload_to='promotions_test_photos/%Y/%m/%d', verbose_name='Фото')),
                ('logotype', models.ImageField(blank=True, upload_to='promotions_test_logotypes/%Y/%m/%d', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, max_length=512, verbose_name='Описание деятельности')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность рекламы')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачен показ рекламы?')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
                ('category', mptt.fields.TreeManyToManyField(blank=True, related_name='promotions', to='reclame.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Место под рекламу',
                'verbose_name_plural': 'Места под рекламу',
                'ordering': ('-created', 'name'),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PromotionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(blank=True, default=False, null=True, verbose_name='Гл. офис?')),
                ('is_not_main', models.BooleanField(blank=True, default=True, null=True, verbose_name='Доп. офис')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активный?')),
                ('address', models.CharField(blank=True, max_length=1024, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Номер тел.')),
                ('schedule_start', models.TimeField(blank=True, null=True, verbose_name='Н. раб. дня (Пон - Пт)')),
                ('schedule_end', models.TimeField(blank=True, null=True, verbose_name='К. раб. дня (Пон - Пт)')),
                ('weekend_start', models.TimeField(blank=True, null=True, verbose_name='Н. раб. дня (Суббота)')),
                ('weekend_end', models.TimeField(blank=True, null=True, verbose_name='К. раб. дня (Суббота)')),
                ('weekend2_start', models.TimeField(blank=True, null=True, verbose_name='Н. раб. дня (Воскресенье)')),
                ('weekend2_end', models.TimeField(blank=True, null=True, verbose_name='К. раб. дня (Воскресенье)')),
                ('dinner_time_start', models.TimeField(blank=True, null=True, verbose_name='Обед. пер-в (н.)')),
                ('dinner_time_end', models.TimeField(blank=True, null=True, verbose_name='Обед. пер-в (к.)')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
                ('promotion', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reclame.Promotion', verbose_name='Место под рекламу (детали)')),
            ],
            options={
                'verbose_name': 'Подробная информация к рекламодателю',
                'verbose_name_plural': 'Подробная информация к рекламодателям',
            },
        ),
    ]
